// This file is "video_model.dart"
import 'package:dart_mappable/dart_mappable.dart';
import '../../domain/entities/video_entity.dart';

// Will be generated by dart_mappable
part 'video_model.mapper.dart';

@MappableClass(caseStyle: CaseStyle.snakeCase)
class VideoModel extends VideoEntity with VideoModelMappable {
  VideoModel({
    required super.id,
    required super.title,
    required super.link,
  });
}

