// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';
import '../../domain/entities/child_entity.dart';

// Will be generated by dart_mappable
part 'child_model.mapper.dart';

@MappableClass(caseStyle: CaseStyle.snakeCase)
class ChildModel extends ChildEntity with ChildModelMappable {
  ChildModel({
    required super.id,
    required super.name,
    required super.age,
    required super.parentId,
    required super.intersets,
  });
}
